Update documentation
votinginfoproject/sms-compose pull request #1
Opened 2017-02-21 23:14 UTC by katrinamariehh

Made updates to the documentation to clarify instructions around deployment; a remaining detail is that I was able to get it all to work by getting a `.env` file from Sean/Chris, that maybe needs to be stored in a more reliable way.

2017-02-21 23:29 UTC, sduckett requested changes
If this pointed to the right repos, I'd 👍

2017-02-21 23:29 UTC, sduckett commented on README.md
> +the [data-processor repository][data-processor] and
I believe you're looking for `sms-web` and `sms-worker`, rather than `data-processor` and `metis`.

2017-02-22 15:08 UTC, katrinamariehh commented on README.md
> +the [data-processor repository][data-processor] and
Good call!  That's what I get for copy-pasting.

2017-02-22 15:29 UTC, sduckett commented on README.md
> +the ec2 instance that is the swarm master.
yeah, good call!

2017-02-28 20:36 UTC, sduckett approved these changes

2017-03-01 22:22 UTC, merged